#!/bin/bash
set -e;

DISPLAYNAME="下载资源"
source "$(dirname "$(readlink -f "$0")")/common/common"

readonly MCVERSION="1.19"
readonly TARGETURL="https://github.com/InventivetalentDev/minecraft-assets/archive/refs/heads/${MCVERSION}.zip"
TMPPATH="${TMPPATH:-/dev/shm/mc_assets/}"

if [ ! -d "/dev/shm" ];then
    TMPPATH="build/temp"
fi;

readonly TMPPATH;

readonly LINKPATH="${PWD}/build/work"

log "创建构建目录..."
mkdir -p "${TMPPATH}" && cd "${TMPPATH}"

log "准备必要的文件..."
download true "${TMPPATH}/assets.zip" "70ce3faf618230d5c38e800f45ef92a4" "Minecraft assets" "${TARGETURL}"

unzip -u "${TMPPATH}/assets.zip" -d "${TMPPATH}" > "${TMPPATH}/unzip.log"

ln "${TMPPATH}/minecraft-assets-${MCVERSION}" "${LINKPATH}" -s

log "完成！"