#!/bin/bash
set -e

DISPLAYNAME="GM4集成"
source "$(dirname "$(readlink -f "$0")")/common/common"

log LWARN "跳过GM4资源包，目前数据包暂未集成。"

exit 0

cd src_xmzs-resources

if [ -d ext_gm4 ];then
    rm -rf ext_gm4;
    mkdir ext_gm4;
else
    mkdir ext_gm4
fi;

#检查是否初始化了submodule
if [ ! -f dep_gm4_resources/requirements.txt ];then
    die 1 "错误：未找到dep_gm4_resources/requirements.txt，是不是submodule没初始化？"
fi;

log "复制GM4文件..."
cp dep_gm4_resources/gm4_resource_pack/* ext_gm4 -r