#!/bin/bash
if [ ! -d build/work ];then
    mkdir -vp build/work
fi

set -e

DISPLAYNAME="字体生成"
source "$(dirname "$(readlink -f "$0")")/common/common"

#生成字体预览

#复制需要的资源
for subpack in src_xmzs-resources/ext_*; do
    cp "$subpack"/assets build/work -r
done;

cp src_xmzs-resources/main/assets build/work -r

readonly FONTGEN="build/temp/fontgen.AppImage"

#获取工具
download true "${FONTGEN}" "47948c3d6547824cd347f9ac6a5567d9" "Fontgen" "https://github.com/XiaMoZhiShi/FontJsonGenerator/releases/download/0.0.3/fontgen.AppImage"

#生成default.json
log "生成字体..."
"${FONTGEN}" --input ./tools/fontconfig.json > "build/temp/fontgen.log"

#复制default中的字体声明到到uniform
cp pack_xmzs-resources/assets/minecraft/font/default.json pack_xmzs-resources/assets/minecraft/font/uniform.json

rm /dev/shm/fontgen_*