#!/bin/bash
if [ ! -d build/work ];then
    mkdir -vp build/work
fi

#还不知道如何确定build/work中是否已构建，所以暂时允许git返回非0
git clone https://github.com/InventivetalentDev/minecraft-assets.git --depth=1 --single-branch --branch 1.18.1 build/work

set -e

cp pack_xmzs-resources/assets build/work/ -r

wget https://github.com/XiaMoZhiShi/FontJsonGenerator/releases/download/0.0.2/fontgen.AppImage -O build/fontgen.AppImage
chmod +x build/fontgen.AppImage

./build/fontgen.AppImage --input ./tools/fontconfig.json
cp pack_xmzs-resources/assets/minecraft/font/default.json pack_xmzs-resources/assets/minecraft/font/uniform.json

mkdir -vp pack_xmzs-resources-bedrock/font/
mv page_0.png pack_xmzs-resources-bedrock/font/glyph_E2.png
mv page_1.png pack_xmzs-resources-bedrock/font/glyph_E3.png

rm /dev/shm/fontgen_*
mv build/fontgen.AppImage build/work