#!/bin/bash
if [ ! -d build/work ];then
    mkdir -vp build/work
fi

#还不知道如何确定build/work中是否已构建，所以暂时允许git返回非0
git clone https://github.com/InventivetalentDev/minecraft-assets.git --depth=1 --single-branch --branch 1.18.1 build/work

set -e

#生成字体预览

#复制需要的资源
for subpack in src_xmzs-resources/ext_*; do
    cp "$subpack"/assets build/work -r
done;

cp src_xmzs-resources/main/assets build/work -r

#获取工具
wget https://github.com/XiaMoZhiShi/FontJsonGenerator/releases/download/0.0.3/fontgen.AppImage -O build/fontgen.AppImage
chmod +x build/fontgen.AppImage

#生成default.json
./build/fontgen.AppImage --input ./tools/fontconfig.json

#复制default中的字体声明到到uniform
cp pack_xmzs-resources/assets/minecraft/font/default.json pack_xmzs-resources/assets/minecraft/font/uniform.json

rm /dev/shm/fontgen_*
mv build/fontgen.AppImage build/work