#!/bin/bash
if [ ! -d build/work ];then
    mkdir -vp build/work
fi

set -e

#生成字体预览

#复制需要的资源
for subpack in src_xmzs-resources/ext_*; do
    cp "$subpack"/assets build/work -r
done;

cp src_xmzs-resources/main/assets build/work -r

#获取工具
if [ -f "build/temp/fontgen.AppImage" ];then
    echo "将使用本地fontgen..."
    cp "build/temp/fontgen.AppImage" "build/fontgen.AppImage"
    chmod +x build/fontgen.AppImage
else
    wget https://github.com/XiaMoZhiShi/FontJsonGenerator/releases/download/0.0.3/fontgen.AppImage -O build/fontgen.AppImage
    chmod +x build/fontgen.AppImage
fi;

#生成default.json
./build/fontgen.AppImage --input ./tools/fontconfig.json

#复制default中的字体声明到到uniform
cp pack_xmzs-resources/assets/minecraft/font/default.json pack_xmzs-resources/assets/minecraft/font/uniform.json

rm /dev/shm/fontgen_*
mv build/fontgen.AppImage build/temp/