#!/bin/bash
set -e

wget https://github.com/XiaMoZhiShi/TextureOverlayer/releases/download/0.0.3/overlayer.AppImage -O build/overlayer.AppImage
chmod +x build/overlayer.AppImage

./build/overlayer.AppImage --input ./tools/xmzs-resources-overlay.json

mv build/overlayer.AppImage build/work