#!/bin/bash
set -e;

readonly MCVERSION="1.19"
readonly TARGETURL="https://github.com/InventivetalentDev/minecraft-assets/archive/refs/heads/${MCVERSION}.zip"
TMPPATH="/dev/shm/mc_assets/"

if [ ! -d "/dev/shm" ];then
    TMPPATH="build/temp"
fi;

readonly TMPPATH;

readonly LINKPATH="${PWD}/build/work"

mkdir -p "${TMPPATH}" && cd "${TMPPATH}"

#好像Unzip暂时不支持从stream读取文件，先下载下来
wget "${TARGETURL}" -O "${TMPPATH}/assets.zip" -c

unzip -u "${TMPPATH}/assets.zip" -d "${TMPPATH}"

ln "${TMPPATH}/minecraft-assets-${MCVERSION}" "${LINKPATH}" -s

#完成后移除压缩文件
rm "${TMPPATH}/assets.zip"