name: 压缩资源包(release)

on:
  release:
     types:
       - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 缓存assets
      uses: actions/cache@v3
      with:
        path: /dev/shm/mc_assets/assets.zip
        key: 1145141919810

    - name: 刷新软件源
      run: sudo apt update

    - name: 安装工具依赖
      run: sudo apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

    - name: 构建
      run: ./makepackage.sh

    - name: 上传到releases
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
